stages:
  - build
  - deploy

build:
  stage: build
  image: node:lts
  script:
    - npm ci
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  image: denoland/deno:latest
  dependencies:
    - build
  script:
    - deno install -A jsr:@deno/deployctl --global
    - cd build
    - deployctl deploy --project=bw-product-website-rebuild jsr:@std/http/file-server
