stages:
  - build
  - deploy

build:
  stage: build
  image: node:lts
  script:
    - npm ci
    - npm run lint
    - npm run build
  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public

deploy:
  stage: deploy
  image: denoland/deno:latest
  dependencies:
    - build
  script:
    - deno install -A jsr:@deno/deployctl --global
    - cd public
    - deployctl deploy --project=bw-product-website-rebuild jsr:@std/http/file-server
