image: node:lts

before_script:
  - npm ci

pages:
  environment: staging
  script:
    - npm run lint
    - npm run build
  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public

  only:
    # Trigger a new build and deploy only when there is a push to the
    # below branch(es)
    - staging
