name: Build and Deploy

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install deployctl
        run: deno install -A jsr:@deno/deployctl --global

      - name: Deploy to staging
        if: github.ref != 'refs/heads/main'
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          cd build
          deployctl deploy --project=bw-product-website-rebuild jsr:@std/http/file-server

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          cd build
          deployctl deploy --project=bw-product-website-rebuild --prod jsr:@std/http/file-server
